DROP DATABASE IF EXISTS DB_SA_SMART40;
CREATE DATABASE DB_SA_SMART40;
USE DB_SA_SMART40;


CREATE TABLE T_SA_EXPEDICAO (
	id_expedicao			BIGINT	NOT NULL,
    vl_posicao_fisica 		TINYINT NOT NULL,
    vl_op_atual				INT     NULL
);

ALTER TABLE T_SA_EXPEDICAO
	ADD CONSTRAINT PK_EXPEDICAO
		PRIMARY KEY(id_expedicao),
	ADD CONSTRAINT CK_EXPEDICAO_POSICAO_FISICA
		CHECK(vl_posicao_fisica BETWEEN 1 AND 12),
	ADD CONSTRAINT UN_EXPEDICAO_POSICAO_FISICA UNIQUE(vl_posicao_fisica);


CREATE TABLE T_SA_PEDIDO (
    id_pedido 				BIGINT 		NOT NULL,
    id_expedicao			BIGINT		NOT NULL,
    vl_ordem_de_producao 	INT 		NOT NULL,
    vl_status 				TINYINT 	NOT NULL,
    tp_pedido 				TINYINT 	NOT NULL,
    vl_cor_tampa			TINYINT		NOT NULL,
    rg_criacao 				TIMESTAMP 	NOT NULL 	DEFAULT CURRENT_TIMESTAMP,
    rg_entrada_expedicao	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
    rg_saida_expedicao		TIMESTAMP	NULL
);

ALTER TABLE T_SA_PEDIDO 
	ADD CONSTRAINT PK_PEDIDO
		PRIMARY KEY(id_pedido),
	ADD CONSTRAINT FK_EXPEDICAO_PEDIDO
		FOREIGN KEY(id_expedicao) 
        REFERENCES T_SA_EXPEDICAO(id_expedicao),
	ADD CONSTRAINT CK_PEDIDO_STATUS
		CHECK (vl_status IN (1, 2, 3)),
	ADD CONSTRAINT CK_PEDIDO_TIPO
		CHECK (tp_pedido IN (1, 2, 3)),
	ADD CONSTRAINT CK_PEDIDO_COR_TAMPA
		CHECK (vl_cor_tampa IN (1, 2, 3));
        
        
CREATE TABLE T_SA_ESTOQUE (
    id_estoque			BIGINT		NOT NULL,	
    vl_posicao_fisica 	TINYINT	 	NOT NULL,
    vl_cor				TINYINT		NOT NULL
);

ALTER TABLE T_SA_ESTOQUE
	ADD CONSTRAINT PK_ESTOQUE
		PRIMARY KEY (id_estoque),
	ADD CONSTRAINT CK_ESTOQUE_COR
		CHECK(vl_cor IN (0, 1, 2, 3)),
	ADD CONSTRAINT CK_ESTOQUE_POSICAO_FISICA
		CHECK(vl_posicao_fisica BETWEEN 1 AND 28),
	ADD CONSTRAINT UN_ESTOQUE_POSICAO_FISICA UNIQUE(vl_posicao_fisica);
        
CREATE TABLE T_SA_BLOCO (
    id_bloco 			BIGINT 		NOT NULL,
    id_pedido			BIGINT		NOT NULL,
    id_estoque	        BIGINT		NOT NULL,
    vl_cor 				TINYINT 	NOT NULL
);

ALTER TABLE T_SA_BLOCO
	ADD CONSTRAINT PK_BLOCO
		PRIMARY KEY(id_bloco),
	ADD CONSTRAINT FK_PEDIDO_BLOCO
		FOREIGN KEY(id_pedido) REFERENCES T_SA_PEDIDO(id_pedido),
	ADD CONSTRAINT FK_ESTOQUE_BLOCO
		FOREIGN KEY(id_estoque) REFERENCES T_SA_ESTOQUE(id_estoque),
	ADD CONSTRAINT UN_BLOCO_ID_ESTOQUE UNIQUE (id_estoque),
	ADD CONSTRAINT CK_BLOCO_COR
		CHECK (vl_cor IN (1, 2, 3));
    
CREATE TABLE T_SA_LAMINA (
    id_lamina	BIGINT	NOT NULL,
    id_bloco	BIGINT	NOT NULL,
    vl_cor		TINYINT	NOT NULL,
    vl_padrao	TINYINT	NOT NULL,
    vl_posicao	TINYINT	NOT NULL
);

ALTER TABLE T_SA_LAMINA
	ADD CONSTRAINT PK_LAMINA
		PRIMARY KEY(id_lamina),
	ADD CONSTRAINT FK_BLOCO_LAMINA
		FOREIGN KEY(id_bloco) REFERENCES T_SA_BLOCO(id_bloco),
	ADD CONSTRAINT CK_LAMINA_COR
		CHECK(vl_cor IN (1, 2, 3, 4, 5, 6)),
	ADD CONSTRAINT CK_LAMINA_PADRAO
		CHECK(vl_padrao IN (0, 1, 2, 3)),
	ADD CONSTRAINT CK_LAMINA_POSICAO
		CHECK(vl_posicao IN (1, 2, 3));