package com.smart.appsa.dto.clp.stream;


public record InfoPedidoStreamDTO(
    int corAndar1,
    int posicaoEstoqueAndar1,
    int corLamina1Andar1,
    int corLamina2Andar1,
    int corLamina3Andar1,
    int padraoLamina1Andar1,
    int padraoLamina2Andar1,
    int padraoLamina3Andar1,
    int processamentoAndar1,
    int corAndar2,
    int posicaoEstoqueAndar2,
    int corLamina1Andar2,
    int corLamina2Andar2,
    int corLamina3Andar2,
    int padraoLamina1Andar2,
    int padraoLamina2Andar2,
    int padraoLamina3Andar2,
    int processamentoAndar2,
    int corAndar3,
    int posicaoEstoqueAndar3,
    int corLamina1Andar3,
    int corLamina2Andar3,
    int corLamina3Andar3,
    int padraoLamina1Andar3,
    int padraoLamina2Andar3,
    int padraoLamina3Andar3,
    int processamentoAndar3,
    int numeroPedido,
    int andares,
    int posicaoExpedicao
) {}
