spring.application.name=appsa

# Propriedades do Banco de Dados
spring.datasource.url=jdbc:mysql://localhost:3306/db_sa_smart40
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Propriedades da JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Propriedades do Server
server.port=${PORT:8080}

# Configurações de Log
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always


spring.thymeleaf.legacy-request-scoped-context=true

clp.ips.expedicao=10.74.241.40
clp.ips.montagem=10.74.241.30
clp.ips.estoque=10.74.241.10
clp.ips.processo=10.74.241.20

clp.endpoints.esp32-tampas.ip=10.74.241.245
clp.endpoints.esp32-tampas.porta=80

# Mostra de onde cada query foi disparada
spring.jpa.properties.hibernate.session.events.log.LOG_QUERIES_SLOWER_THAN_MS=0
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Melhor ainda: stack trace completo
spring.jpa.properties.hibernate.generate_statistics=true
logging.level.org.hibernate.stat=DEBUG

spring.jpa.properties.hibernate.session_factory.statement_inspector=com.smart.appsa.config.QueryTraceInspector